apiVersion: v2
name: octopus
description: A Helm chart for Rancher Octopus App

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.1.0

dependencies: # A list of the chart requirements (optional)
  - name: ble-adaptor
    version: 0.1.0
    condition: ble-adaptor.enabled
    tags:
      - octopus-adaptor
    enabled: true
  - name: modbus-adaptor
    version: 0.1.0
    condition: modbus-adaptor.enabled
    tags:
      - octopus-adaptor
    enabled: true
  - name: edge-ui
    version: 0.1.0
    condition: edge-ui.enabled
    tags:
    - edge-ui
    enabled: true
