kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "octopus-ui.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "octopus-ui.fullname" . }}
  namespace: {{ .Values.apiNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "octopus-ui.fullname" . }}
  namespace: {{ .Values.apiNamespace }}
  labels:
    {{- include "octopus-ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
