apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "opcua-adaptor.fullname" . }}-role
  labels:
  {{- include "modbus-adaptor.labels" . | nindent 4 }}
rules:
- apiGroups:
  - devices.edge.cattle.io
  resources:
  - opcuadevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.edge.cattle.io
  resources:
  - opcuadevices/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "opcua-adaptor.fullname" . }}-rolebinding
  labels:
  {{- include "opcua-adaptor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "opcua-adaptor.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
